### ISSUE TITLE
go binary path detection is broken

### ISSUE THREAD

**Issue by fserb** [sublimelsp/LSP-gopls#43]
Currently, LSP-gopls calls `cls._is_go_installed()` which eventually calls `shutil.which("go")`. This checks if the `go` binary is available on Sublime's `PATH`, which may not be the same as the env variables passed to gopls execution.

In my system (MacOS Homebrew), ST4's PATH is broken, but gopls has the correct env vars. Everything works EXCEPT for the manual check for the go binary. If I comment those two lines, the whole thing works just fine. 

Either remove the manual binary check or do it with proper env vars (the one passed to gopls).

**Comment by fserb** [comment]
Yes. The PATH is correct, as in gopls is found and gopls has the correct env to find go.

The thing that is broken is the early check that LSP-gopls is doing to find "go" using Sublime's PATH.

**Comment by rchl** [comment]
Might be a correct thing to do to just defer to `gopls` handling missing `go`. I wonder what is the server's feedback then.

**Comment by rchl** [comment]
Well, I've tried and the package first checks for `go` (`if not cls._is_go_installed():`) so that it can use it later to run `go install golang.org/x/tools/gopls`.

So `go` is actually required for this package to be able to manage the `gopls` installation.

If you want to opt-out from this package managing the server then that's I guess not supported right now. We generally are hesitant to provide any support for that since the whole point of this package is that it manages the server for you and makes sure that settings it defines and extra commands work with the specific version that is used. If you are using your own gopls version then we can't guarantee any of that.

**Comment by fserb** [comment]
okey. But then, are the instructions correct? https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers

It's talking about adding env/PATH, but those are never used to check for 'go' to begin with.

**Comment by rchl** [comment]
Those instructions explain how to make sure that the `os.environ.PATH` used by the ST's python runtime is set properly. And `shutil.which` uses that to lookup binaries. So those **are** used to check for `go` in case of this package.

In your case you said:

> This checks if the go binary is available on Sublime's PATH, which may not be the same as the env variables passed to gopls execution.

but at the point at which you are getting the issue in this package the `gopls` is not even in the picture yet so how is it relevant?

You could update ST's path using instructions from the link you've posted to make it the same as in the terminal and it would probably work.

**Comment by fserb** [comment]
Are you sure?

For Mac, the instructions seem weird. `.profile is NOT loaded when you open an app. It only works if you start sublime from the terminal. 

I was referring the the alternative suggestions that say "to update the server PATH using the env parameter in your LSP configuration file". I'm pretty sure those are not automatically added to `os.environ.PATH` and won't be used on `shutil.which`.

Sorry, my mistake I meant `go` execution. If you check here: https://github.com/sublimelsp/LSP-gopls/blob/main/plugin/plugin.py#L158

You can see that the go binary is being run with a different env, which I assumed includes the settings (suggested on the alternative method on the documentation). Those are not being correctly considered on `shutil.which`. Which is why, on my system, that has the correct env/PATH settings, but the wrong os.environ.PATH, the check fails, but the command works.

**Comment by rchl** [comment]
> For Mac, the instructions seem weird. `.profile is NOT loaded when you open an app. It only works if you start sublime from the terminal.

For Mac it's `. zprofile` since zsh is the default shell these days. And it's ST that does evaluate those manually so it's not dependant on how it's started.

**Comment by fserb** [comment]
hmm. I'll try that.

But maybe it would be ok to just remove that check, since it's checking for the wrong thing anyways and is not supporting the per-language/env vars. I think other LSP-* plugins don't manually check for that. You can just let the execution fail, no?

**Comment by rchl** [comment]
With the check it fails with `go binary not found in $PATH` error and without with `[Errno 2] No such file or directory: 'go'`. I think our custom error message makes it clearer why it failed.

But are you saying that the `go install golang.org/x/tools/gopls` that the plugin executes doesn't fail for you but it fails later when starting `gopls`?

**Comment by fserb** [comment]
No, no, it's worse than that.  Only [this check](https://github.com/sublimelsp/LSP-gopls/blob/main/plugin/plugin.py#L148) fails and everything else works. My currently working LSP-gopls is just those two lines (148-149) commented out.

**Comment by rchl** [comment]
So `subprocess.Popen('go')` works but `shutil.which` doesn't? That's strange. I remember there being some symlink specific issues with `shutil.which` implementation in Python 3.3 (which is used by the plugin host). That might be it if your `go` binary is a symlink. But if that's the case then it would make sense to remove that check and instead catch the `subprocess.Popen('go')` call.

**Comment by fserb** [comment]
At least in my system, I'm pretty sure it's a PATH issue. 

`subprocess.Popen` uses the passed `env.PATH`, while `shutil.which` doesn't.

My `go` binary is available on the PATH provided by my LSP configuration, but not on the default Sublime PATH. If you want to keep the `which`, you need to run it on the configured PATH, not on the default.

**Comment by rchl** [comment]
- `shutil.which` uses PATH of the process that is calling it.
- `subprocess.Popen` gets passed env created this way:

```py
        env_vars = dict(os.environ)
        env_vars['GO111MODULE'] = 'on'
        env_vars['GOPATH'] = cls.basedir()
        env_vars['GOBIN'] = os.path.join(cls.basedir(), 'bin')
        env_vars['GOCACHE'] = os.path.join(cls.basedir(), 'go-build')
```

So it doesn't modify PATH. Did you mean that the extra `GO*` variables make a difference? They shouldn't with `go` lookup but maybe they do with what happens when it's running...

**Comment by TerminalFi** [comment]
@fserb What is the desired outcome here? Do you want to self manage gopls ?

**Comment by fserb** [comment]
I was just trying to make LSP-gopls work without having to clone the module.

I spent some more time messing with this today and I was able to make ST to load my full PATH. So now LSP-gopls seems to be working fine again. From my perspective we can close this for now.

Although my suggestion would be: the second set of instructions on how to fix PATH on the Sublime-LSP page talk about adding env/PATH to the configuration file. env/PATH is currently NOT supported by the way LSP-gopls is trying to look for go. So maybe an outcome here would be to support that?

**Comment by TerminalFi** [comment]
I’m still unsure what needs to change on the LSP-gopls side. It loads the same PATH as ST.

**Comment by fserb** [comment]
Pretend for a second that ST PATH doesn't contain any path with go. According to the [instructions](https://lsp.sublimetext.io/troubleshooting/#updating-the-path-used-by-lsp-servers):

> Another solution could be (at least on Linux) to update the server PATH using the env parameter in your LSP configuration file. The following template can be used where:
>
> <your_language_server_name> is the server name
> <added_path> is the directory needed for the server to behave correctly
> "<your_language_server_name>":
> {
>    // ...
>
>    "env":
>    {
>        "PATH": "<added_path>:/usr/local/bin"
>    }
> }

Make this works with LSP-gopls.

**Comment by TerminalFi** [comment]
Gotcha, this makes sense. Let me see what is needed to get this in.

**Comment by cixtor** [comment]
Adding to the conversation, in version [LSP-gopls (1.2.5)](https://github.com/sublimelsp/LSP-gopls/releases/tag/v1.2.5) there is a function called `needs_update_or_installation`, which returns `True` if `gopls` is installed —or— if the content a `VERSION` file is different than the global variable `VERSION`, which in this version of the plugin is `0.11.0`.

I install and update `gopls` via [Homebrew](https://github.com/Homebrew/brew).

The problem I have is that the plugin always tries to update-or-install gopls in the so called “storage path”, which after some debugging I determined to be `~/Library/Caches/Sublime Text/Package Storage/LSP-gopls/bin/gopls`, which I do not want to use as it differs from the system-wide installation approach that Homebrew assumes.

I already verified that `os.environ` inside function `_set_env_vars` has the correct values in `PATH` so, technically speaking, the plugin should be able to detect the existence of both `go` and `gopls` and stop any attempt to install the binary.

---

Maybe unrelated… I see that the default [LSP-gopls.sublime-settings](https://github.com/sublimelsp/LSP-gopls/blob/main/LSP-gopls.sublime-settings) has the following value: `"${storage_path}/LSP-gopls/bin/gopls"`, which is exactly the path that I am observing in the SublimeText console. However, when I override the `“command”` setting with simply `gopls` (since the binary is already in PATH and SublimeText can see it), the plugin ignores the value and continues checking for the one in “Storage Path”.

---

For now, I am going to create a symbolic link of `/usr/local/bin/gopls`, which is already a symbolic link of `/usr/local/Cellar/gopls/<VERSION>/bin/gopls`, in `~/Library/Caches/Sublime Text/Package Storage/LSP-gopls/bin/gopls` to stops all attempts to install or update that program, but I would appreciate if you could modify the binary path detection because it is currently making unnecessary assumptions.

**Comment by TerminalFi** [comment]
I've got an update coming that supplies a way to fix this
